print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/arsenelakpa/Documents/Spring Semester 2018/CS 4455/annica-game/Assets/AppContent/Models/protagonist.mb"`)
{		
	file -o "/Users/arsenelakpa/Documents/Spring Semester 2018/CS 4455/annica-game/Assets/AppContent/Models/protagonist.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/arsenelakpa/Documents/Spring Semester 2018/CS 4455/annica-game/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/arsenelakpa/Documents/Spring Semester 2018/CS 4455/annica-game/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/arsenelakpa/Documents/Spring Semester 2018/CS 4455/annica-game/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
